### ISSUE TITLE
Latest mysql connector versions fail for utf8 chars

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/ispyb-api#183]
When trying to open a connection to ispyb I get the following error:
```python
Traceback (most recent call last):
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1513, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 1140, in dec_inner
    return (yield from plan)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 325, in run_wrapper
    yield from contingency_wrapper(plan,
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 575, in contingency_wrapper
    ret = yield from plan
  File "/dls_sw/i03/software/artemis/src/artemis/fast_grid_scan_plan.py", line 82, in run_gridscan
    with ispyb as ispyb_ids, NexusWriter(
  File "/dls_sw/i03/software/artemis/src/artemis/ispyb/store_in_ispyb.py", line 46, in __enter__
    ) = self.store_grid_scan(self.full_params)
  File "/dls_sw/i03/software/artemis/src/artemis/ispyb/store_in_ispyb.py", line 77, in store_grid_scan
    with ispyb.open(self.ISPYB_CONFIG_FILE) as self.conn:
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/ispyb/__init__.py", line 55, in open
    conn = Connector(**credentials)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/ispyb/connector/mysqlsp/main.py", line 30, in __init__
    self.connect(user=user, pw=pw, host=host, db=db, port=port)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/ispyb/connector/mysqlsp/main.py", line 53, in connect
    self.conn = mysql.connector.connect(
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/pooling.py", line 287, in connect
    return MySQLConnection(*args, **kwargs)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/connection.py", line 137, in __init__
    self.connect(**kwargs)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1095, in connect
    self._open_connection()
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/connection.py", line 544, in _open_connection
    self.set_converter_class(self._converter_class)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1271, in set_converter_class
    self.converter = convclass(charset_name, self._use_unicode)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/conversion.py", line 136, in __init__
    MySQLConverterBase.__init__(self, charset, use_unicode, str_fallback)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/conversion.py", line 59, in __init__
    self.set_charset(charset)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/conversion.py", line 73, in set_charset
    self.charset_id = CharacterSet.get_charset_info(self.charset)[0]
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/constants.py", line 775, in get_charset_info
    info = cls.get_default_collation(charset)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/mysql/connector/constants.py", line 746, in get_default_collation
    raise ProgrammingError(f"Character set '{charset}' unsupported")
mysql.connector.errors.ProgrammingError: Character set 'utf8' unsupported
```
According to https://stackoverflow.com/questions/73244027/character-set-utf8-unsupported-in-python-mysql-connector the fix is to either pin mysql-connector version or use a specific `mariadb` connector.

**Comment by DominicOram** [comment]
@KarlLevik can we use a mariadb connector or do we need to maintain compatibility with mysql? It's frustrating to have to pin versions forever

**Comment by rjgildea** [comment]
See also https://github.com/DiamondLightSource/ispyb-api/pull/181#discussion_r942682126. Fixed in principle by [these changes](https://github.com/DiamondLightSource/ispyb-api/compare/charset-latin1) although I don't fully understand why or if this is the correct fix.

**Comment by DominicOram** [comment]
I personally don't mind a fix that we don't 100% understand. I also see now it's pinned in the `requirements.txt` but not in the `setup.cfg`, meaning a `pip install ispyb` gets the wrong version. If we're not going to merge your fix we should at least pin the version in the `setup.cfg`

**Comment by KarlLevik** [comment]
Good point re: `setup.cfg`, I didn't realise that. 

The `latin1` workaround limits us to reading(*) and writing latin1 characters, but that might be sufficient for our use-cases. I don't mind which of these solutions are implemented. 

\* characters beyond this will be converted

**Comment by DominicOram** [comment]
Hmm... I suspect we will want utf8 chars at some point. I think between the two pinning the version seems less likely to limit us. I can make a PR for this
